<?php

namespace Database\Seeders;

use App\Domains\Coupon\Models\Coupon;
use Illuminate\Database\Seeder;

class CouponSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coupons = [
            [
                'code' => 'SUMMER2026',
                'description' => 'Special summer discount for all services',
                'description_ar' => 'خصم صيفي خاص لجميع الخدمات',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'minimum_order_amount' => 50,
                'maximum_discount_amount' => 100,
                'usage_limit' => 100,
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(30),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'WELCOME10',
                'description' => 'Welcome discount for new customers',
                'description_ar' => 'خصم ترحيبي للعملاء الجدد',
                'discount_type' => 'percentage',
                'discount_value' => 10,
                'minimum_order_amount' => 30,
                'maximum_discount_amount' => 50,
                'usage_limit' => 200,
                'start_date' => now()->subDays(10),
                'end_date' => now()->addDays(60),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'CLEAN25',
                'description' => 'Discount for cleaning services',
                'description_ar' => 'خصم لخدمات التنظيف',
                'discount_type' => 'percentage',
                'discount_value' => 25,
                'minimum_order_amount' => 40,
                'maximum_discount_amount' => 75,
                'usage_limit' => 50,
                'start_date' => now()->subDays(3),
                'end_date' => now()->addDays(20),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'FIXED20',
                'description' => 'Fixed amount discount',
                'description_ar' => 'خصم بمبلغ ثابت',
                'discount_type' => 'fixed',
                'discount_value' => 20,
                'minimum_order_amount' => 100,
                'maximum_discount_amount' => null,
                'usage_limit' => 150,
                'start_date' => now()->subDays(7),
                'end_date' => now()->addDays(45),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'RAMADAN30',
                'description' => 'Ramadan special offer',
                'description_ar' => 'عرض خاص لشهر رمضان',
                'discount_type' => 'percentage',
                'discount_value' => 30,
                'minimum_order_amount' => 60,
                'maximum_discount_amount' => 150,
                'usage_limit' => 80,
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(25),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'MAINTENANCE15',
                'description' => 'Discount for maintenance services',
                'description_ar' => 'خصم لخدمات الصيانة',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'minimum_order_amount' => 35,
                'maximum_discount_amount' => 60,
                'usage_limit' => 120,
                'start_date' => now()->subDays(4),
                'end_date' => now()->addDays(35),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'FIRSTORDER',
                'description' => 'First order discount',
                'description_ar' => 'خصم الطلب الأول',
                'discount_type' => 'percentage',
                'discount_value' => 15,
                'minimum_order_amount' => 25,
                'maximum_discount_amount' => 40,
                'usage_limit' => 300,
                'start_date' => now()->subDays(15),
                'end_date' => now()->addDays(90),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'WEEKEND50',
                'description' => 'Weekend special discount',
                'description_ar' => 'خصم خاص لعطلة نهاية الأسبوع',
                'discount_type' => 'fixed',
                'discount_value' => 10,
                'minimum_order_amount' => 80,
                'maximum_discount_amount' => null,
                'usage_limit' => 70,
                'start_date' => now()->subDays(1),
                'end_date' => now()->addDays(15),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'LOYALTY20',
                'description' => 'Loyalty program discount',
                'description_ar' => 'خصم برنامج الولاء',
                'discount_type' => 'percentage',
                'discount_value' => 20,
                'minimum_order_amount' => 100,
                'maximum_discount_amount' => 200,
                'usage_limit' => 60,
                'start_date' => now()->subDays(8),
                'end_date' => now()->addDays(50),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'code' => 'FLASHSALE',
                'description' => 'Flash sale limited time offer',
                'description_ar' => 'عرض بيع سريع لفترة محدودة',
                'discount_type' => 'percentage',
                'discount_value' => 35,
                'minimum_order_amount' => 70,
                'maximum_discount_amount' => 120,
                'usage_limit' => 40,
                'start_date' => now(),
                'end_date' => now()->addDays(7),
                'is_active' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
        ];

        foreach ($coupons as $coupon) {
            Coupon::create($coupon);
        }
    }
}
