<?php

namespace Database\Seeders;

use App\Domains\Offer\Models\Offer;
use App\Domains\Coupon\Models\Coupon;
use App\Domains\AppService\Models\AppService;
use Illuminate\Database\Seeder;

class OfferSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $offers = [
            [
                'title' => 'عرض الصيف الخاص',
                'title_ar' => 'عرض الصيف الخاص',
                'description' => 'Amazing summer discounts on all services',
                'description_ar' => 'خصومات صيفية مذهلة على جميع الخدمات',
                'coupon_id' => Coupon::where('code', 'SUMMER2026')->first()->id ?? null,
                'category_id' => 1,
                'app_service_id' => AppService::where('name', 'خدمات تنظيف المنازل')->first()->id ?? null,
                'discount_percentage' => 25,
                'original_price' => 100,
                'offer_price' => 75,
                'currency' => 'JOD',
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(30),
                'is_active' => true,
                'is_featured' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض الترحيب',
                'title_ar' => 'عرض الترحيب',
                'description' => 'Special welcome offer for new customers',
                'description_ar' => 'عرض ترحيبي خاص للعملاء الجدد',
                'coupon_id' => Coupon::where('code', 'WELCOME10')->first()->id ?? null,
                'category_id' => 2,
                'app_service_id' => AppService::where('name', 'خدمات النقل')->first()->id ?? null,
                'discount_percentage' => 15,
                'original_price' => 80,
                'offer_price' => 68,
                'currency' => 'JOD',
                'start_date' => now()->subDays(10),
                'end_date' => now()->addDays(60),
                'is_active' => true,
                'is_featured' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض التنظيف',
                'title_ar' => 'عرض التنظيف',
                'description' => 'Professional cleaning at great prices',
                'description_ar' => 'تنظيف احترافي بأسعار ممتازة',
                'coupon_id' => Coupon::where('code', 'CLEAN25')->first()->id ?? null,
                'category_id' => 1,
                'app_service_id' => AppService::where('name', 'خدمات النظافة العامة')->first()->id ?? null,
                'discount_percentage' => 30,
                'original_price' => 120,
                'offer_price' => 84,
                'currency' => 'JOD',
                'start_date' => now()->subDays(3),
                'end_date' => now()->addDays(20),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض الصيانة',
                'title_ar' => 'عرض الصيانة',
                'description' => 'Home maintenance special offer',
                'description_ar' => 'عرض خاص لصيانة المنازل',
                'coupon_id' => Coupon::where('code', 'MAINTENANCE15')->first()->id ?? null,
                'category_id' => 3,
                'app_service_id' => AppService::where('name', 'خدمات الصيانة')->first()->id ?? null,
                'discount_percentage' => 20,
                'original_price' => 150,
                'offer_price' => 120,
                'currency' => 'JOD',
                'start_date' => now()->subDays(4),
                'end_date' => now()->addDays(35),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض الحدائق',
                'title_ar' => 'عرض الحدائق',
                'description' => 'Beautiful garden services at discount',
                'description_ar' => 'خدمات حدائق جميلة بخصم',
                'coupon_id' => null,
                'category_id' => 4,
                'app_service_id' => AppService::where('name', 'خدمات الحدائق')->first()->id ?? null,
                'discount_percentage' => 18,
                'original_price' => 200,
                'offer_price' => 164,
                'currency' => 'JOD',
                'start_date' => now()->subDays(6),
                'end_date' => now()->addDays(40),
                'is_active' => true,
                'is_featured' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض التكييف',
                'title_ar' => 'عرض التكييف',
                'description' => 'Air conditioning services special',
                'description_ar' => 'خدمات التكييف بعرض خاص',
                'coupon_id' => null,
                'category_id' => 5,
                'app_service_id' => AppService::where('name', 'خدمات التكييف')->first()->id ?? null,
                'discount_percentage' => 22,
                'original_price' => 180,
                'offer_price' => 140,
                'currency' => 'JOD',
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(25),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض الكهرباء',
                'title_ar' => 'عرض الكهرباء',
                'description' => 'Electrical services at great rates',
                'description_ar' => 'خدمات كهربائية بأسعار ممتازة',
                'coupon_id' => Coupon::where('code', 'FIXED20')->first()->id ?? null,
                'category_id' => 6,
                'app_service_id' => AppService::where('name', 'خدمات الكهرباء')->first()->id ?? null,
                'discount_percentage' => 15,
                'original_price' => 90,
                'offer_price' => 76,
                'currency' => 'JOD',
                'start_date' => now()->subDays(7),
                'end_date' => now()->addDays(45),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض السباكة',
                'title_ar' => 'عرض السباكة',
                'description' => 'Plumbing services discount offer',
                'description_ar' => 'عرض خصم لخدمات السباكة',
                'coupon_id' => null,
                'category_id' => 7,
                'app_service_id' => AppService::where('name', 'خدمات السباكة')->first()->id ?? null,
                'discount_percentage' => 20,
                'original_price' => 110,
                'offer_price' => 88,
                'currency' => 'JOD',
                'start_date' => now()->subDays(5),
                'end_date' => now()->addDays(30),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض الطلاء',
                'title_ar' => 'عرض الطلاء',
                'description' => 'Painting and decoration special',
                'description_ar' => 'الطلاء والديكور بعرض خاص',
                'coupon_id' => Coupon::where('code', 'RAMADAN30')->first()->id ?? null,
                'category_id' => 8,
                'app_service_id' => AppService::where('name', 'خدمات الطلاء')->first()->id ?? null,
                'discount_percentage' => 25,
                'original_price' => 250,
                'offer_price' => 187,
                'currency' => 'JOD',
                'start_date' => now()->subDays(2),
                'end_date' => now()->addDays(25),
                'is_active' => true,
                'is_featured' => true,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
            [
                'title' => 'عرض التركيب',
                'title_ar' => 'عرض التركيب',
                'description' => 'Installation services at discount',
                'description_ar' => 'خدمات التركيب بخصم',
                'coupon_id' => null,
                'category_id' => 9,
                'app_service_id' => AppService::where('name', 'خدمات التركيب')->first()->id ?? null,
                'discount_percentage' => 12,
                'original_price' => 130,
                'offer_price' => 114,
                'currency' => 'JOD',
                'start_date' => now()->subDays(8),
                'end_date' => now()->addDays(50),
                'is_active' => true,
                'is_featured' => false,
                'created_by_id' => 1,
                'updated_by_id' => 1,
            ],
        ];

        foreach ($offers as $offer) {
            Offer::create($offer);
        }
    }
}
